import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { storyblokInit, apiPlugin } from '@storyblok/react/rsc';
import StoryblokProvider from "./components/StoryblokProvider";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const initStoryblok = () => {
  const token = process.env.STORYBLOK_ACCESS_TOKEN;
  const region = process.env.STORYBLOK_REGION as "us" | "eu" | undefined;

  if (!token) {
    throw new Error(
      "Missing STORYBLOK_ACCESS_TOKEN. Set a preview token in your environment (e.g., .env.local) and restart the dev server."
    );
  };
  const cachedFetch = (input: RequestInfo | URL, init?: RequestInit): Promise<Response> => {
    return fetch (input, {
      ...init,
      cache: process.env.NODE_ENV === "development" ? "no-store" : "force-cache",
    });
  };

  storyblokInit({
    accessToken: token, // aus .env
    use: [apiPlugin],
    apiOptions: {
      fetch: cachedFetch,
      region,
      cache: {
        type: 'none',
        clear: 'auto',
      },
    },
  });
};

initStoryblok();
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} `}>
        <header className="bg-white">
          <nav className="text-gray-800 font-bold container mx-auto px-4 w-full py-8 flex justify-between">
            <Link href={"/"}>Home</Link>
            <Link href={"/tours"}>Tours</Link>
          </nav>
        </header>
        <StoryblokProvider>
          {children}
        </StoryblokProvider>
      </body>
    </html>
  );
}